# Settings for the Makefile which define
# various things like the names, paths, etc pp
#

# GRF Name
CAT_NAME     = OpenSFX
FILENAME     = opensfx
CAT_SHORTNAME= OSFX
CAT_NIGHTLYNAME = nightly
CAT_DESCRIPTION = OpenSFX sound replacement set for OpenTTD. Freely available under the terms of the Creative Commons Sampling Plus 1.0 License.
CAT_ORIGIN   = default = Please redownload from BaNaNas.

OBS_FILE           = opensfx.obs
LICENSE_FILENAME   = docs/license.txt
CHANGELOG_FILENAME = docs/changelog.txt
README_FILENAME    = docs/readme.txt

# Build parameters and programmes
# Usually this needs no change.
CATCODEC_FLAGS = -e
TAR_FLAGS      = cf
ZIP_FLAGS      = -r -j
BZIP_FLAGS     = -k9f

# Macs have a different md5 command than linux or mingw envirnoment:
ifeq ($(OSTYPE),Darwin)
MD5SUM   = md5 -r
else
MD5SUM   = md5sum
endif
CATCODEC = CATcodec
TAR      = tar
ZIP      = zip
BZIP     = bzip2

SFO_SUFFIX   = sfo
TAR_SUFFIX   = tar
CAT_SUFFIX   = cat
ZIP_SUFFIX   = zip
BZIP2_SUFFIX = bz2
TXT_SUFFIX   = txt
PTXT_SUFFIX  = ptxt
DEP_SUFFIX   = d

# Things to replace in the readme file
#CAT_TITLE_DUMMY = {{CAT_TITLE}}
#OBS_FILE_DUMMY  = {{OBS_FILE}}
#REVISION_DUMMY  = {{CAT_REVISION}}

# Paths defining the directory layout
SRCDIR   = src
DOCDIR   = docs

CAT_FILENAME   = $(addsuffix .$(CAT_SUFFIX),$(FILENAME))
SFO_FILENAME   = $(addsuffix .$(SFO_SUFFIX),$(FILENAME))
DIR_BASE       = $(FILENAME)-
VERSION_STRING = $(shell [ -n "$(REPO_TAGS)" ] && echo $(REPO_TAGS)$(CAT_MODIFIED) || echo $(CAT_NIGHTLYNAME)-r$(CAT_REVISION)$(CAT_MODIFIED))
DIR_NIGHTLY    = $(DIR_BASE)$(CAT_NIGHTLYNAME)
DIR_RELEASE    = $(DIR_BASE)$(VERSION_STRING)

MAINDIRS       = $(SRCDIR) $(DOCDIR)
DEP_FILENAMES  = $(addsuffix .$(DEP_SUFFIX),$(FILENAME))

CAT_TITLE     = $(CAT_NAME) $(VERSION_STRING)
TAR_FILENAME  = $(DIR_NIGHTLY).$(TAR_SUFFIX)
BZIP_FILENAME = $(TAR_FILENAME).$(BZIP2_SUFFIX)
ZIP_FILENAME  = $(DIR_RELEASE).$(ZIP_SUFFIX)
DOC_FILENAMES = $(addsuffix .$(TXT_SUFFIX),$(basename $(LICENSE_FILENAME) $(CHANGELOG_FILENAME) $(README_FILENAME)))

BUNDLE_FILES = $(SRCDIR)/$(CAT_FILENAME) $(DOC_FILENAMES) $(OBS_FILE)

# Remove the @ when you want a more verbose output.
_V := @
_E := @echo
