# This file defines the principal settings for this project

REPO_NAME          := OpenSFX
REPO_SHORTNAME     := OSFX
REPO_ORIGIN         = default = Please redownload from BaNaNaS.

GENERATE_GRF       := sound

BASE_FILENAME      := opensfx
SOUND_FILE         := $(BASE_FILENAME).cat
OBS_FILE           := $(BASE_FILENAME).obs

SOUND_FILES        := $(ls src/wav/*.wav)
LANG_FILES         := $(ls lang/*.lng)

BUNDLE_FILES        = $(BASE_FILENAME).obs $(DOC_FILES) $(SOUND_FILES)

MD5_SRC_FILENAME   := $(BASE_FILENAME).obs

CATCODEC           := catcodec
CATCODEC_FLAGS     := -e

# If everything is default, you don't need the rest:

# comment out those dirs which are not in use
SCRIPT_DIR         := scripts
SRC_DIR            := src

