name: Testing

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  testing:
    name: Testing
    uses: OpenTTD/actions/.github/workflows/rw-entry-testing-baseset.yml@v5
    with:
      apt-packages: catcodec
      name: opensfx
